[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node_modules/.bin/next start -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
